import {useEffect} from 'react';
import styles from '../styles/Home.module.css'
import Head from 'next/head'


const About =()=> {
  // useEffect(() => {
  //   window.scrollTo(0, 0)
  // }, [])
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="aboutPage">
      <div className="aboutHeading">
        <h1>About</h1>
      </div>
      <div className="aboutContent">
        <h2>Sed id semper risus in hendrerit gravida dignissim convallis.</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In eu mi bibendum neque egestas congue quisque egestas diam. Eget mauris pharetra et ultrices neque ornare aenean euismod elementum. Ornare arcu dui vivamus arcu felis bibendum ut. Sed id semper risus in hendrerit gravida rutrum. Gravida arcu ac tortor dignissim convallis aenean et tortor.
        </p>
        <p>
            At volutpat diam ut venenatis tellus in. Donec ultrices tincidunt arcu non sodales neque sodales ut. Eu sem integer vitae justo eget magna fermentum. Tristique nulla aliquet enim tortor at auctor. Nulla facilisi etiam dignissim diam quis enim. Nam at lectus urna duis convallis convallis tellus id.
        </p>
        <p>
            Etiam erat velit scelerisque in dictum non consectetur a erat. Donec massa sapien faucibus et molestie ac feugiat. Feugiat in fermentum posuere urna nec tincidunt. Quis eleifend quam adipiscing vitae proin sagittis. Nunc sed augue lacus viverra vitae congue. Amet justo donec enim diam vulputate ut pharetra sit amet. Risus sed vulputate odio ut enim blandit volutpat. Vel turpis nunc eget lorem. Praesent semper feugiat nibh sed pulvinar proin gravida. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Lacus viverra vitae congue eu consequat.
        </p>
        
      </div>
    </main>

    </>
    



  )
}

export default About;